### ISSUE TITLE
Config file not present for generating client cert using CSR in script 3

### ISSUE THREAD

**Issue by Dodain** [wxleong/optiga-tpm-2021-e2-training-day1#1]
In https://github.com/wxleong/optiga-tpm-2021-e2-training-day1/blob/master/ubuntu/exercise-1-mssim-openssl-cli/3_gen-client-crt.sh for generating CA signed client cert "yes | openssl ca -config config -in tpm.csr -out tpm.crt" is used but the custom "config" file isn't created because of which the command can not be executed.

**Comment by wxleong** [comment]
The config file is in `~/optiga-tpm-2021-e2-training-day1/ubuntu/exercise-1-mssim-openssl-cli`. Please `cd` to the directory before executing the script as instructed in [Exercise 1](https://github.com/wxleong/optiga-tpm-2021-e2-training-day1/tree/master/ubuntu#exercise-1)
